
import { BibleBook, BibleDivision } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
  // Antigo Testamento
  { name: 'Gênesis', division: BibleDivision.PENTATEUCH, chapters: 50 },
  { name: 'Êxodo', division: BibleDivision.PENTATEUCH, chapters: 40 },
  { name: 'Levítico', division: BibleDivision.PENTATEUCH, chapters: 27 },
  { name: 'Números', division: BibleDivision.PENTATEUCH, chapters: 36 },
  { name: 'Deuteronômio', division: BibleDivision.PENTATEUCH, chapters: 34 },
  { name: 'Josué', division: BibleDivision.HISTORY, chapters: 24 },
  { name: 'Juízes', division: BibleDivision.HISTORY, chapters: 21 },
  { name: 'Rute', division: BibleDivision.HISTORY, chapters: 4 },
  { name: '1 Samuel', division: BibleDivision.HISTORY, chapters: 31 },
  { name: '2 Samuel', division: BibleDivision.HISTORY, chapters: 24 },
  { name: '1 Reis', division: BibleDivision.HISTORY, chapters: 22 },
  { name: '2 Reis', division: BibleDivision.HISTORY, chapters: 25 },
  { name: '1 Crônicas', division: BibleDivision.HISTORY, chapters: 29 },
  { name: '2 Crônicas', division: BibleDivision.HISTORY, chapters: 36 },
  { name: 'Esdras', division: BibleDivision.HISTORY, chapters: 10 },
  { name: 'Neemias', division: BibleDivision.HISTORY, chapters: 13 },
  { name: 'Ester', division: BibleDivision.HISTORY, chapters: 10 },
  { name: 'Jó', division: BibleDivision.POETRY, chapters: 42 },
  { name: 'Salmos', division: BibleDivision.POETRY, chapters: 150 },
  { name: 'Provérbios', division: BibleDivision.POETRY, chapters: 31 },
  { name: 'Eclesiastes', division: BibleDivision.POETRY, chapters: 12 },
  { name: 'Cantares', division: BibleDivision.POETRY, chapters: 8 },
  { name: 'Isaías', division: BibleDivision.MAJOR_PROPHETS, chapters: 66 },
  { name: 'Jeremias', division: BibleDivision.MAJOR_PROPHETS, chapters: 52 },
  { name: 'Lamentações', division: BibleDivision.MAJOR_PROPHETS, chapters: 5 },
  { name: 'Ezequiel', division: BibleDivision.MAJOR_PROPHETS, chapters: 48 },
  { name: 'Daniel', division: BibleDivision.MAJOR_PROPHETS, chapters: 12 },
  { name: 'Oseias', division: BibleDivision.MINOR_PROPHETS, chapters: 14 },
  { name: 'Joel', division: BibleDivision.MINOR_PROPHETS, chapters: 3 },
  { name: 'Amós', division: BibleDivision.MINOR_PROPHETS, chapters: 9 },
  { name: 'Obadias', division: BibleDivision.MINOR_PROPHETS, chapters: 1 },
  { name: 'Jonas', division: BibleDivision.MINOR_PROPHETS, chapters: 4 },
  { name: 'Miqueias', division: BibleDivision.MINOR_PROPHETS, chapters: 7 },
  { name: 'Naum', division: BibleDivision.MINOR_PROPHETS, chapters: 3 },
  { name: 'Habacuque', division: BibleDivision.MINOR_PROPHETS, chapters: 3 },
  { name: 'Sofonias', division: BibleDivision.MINOR_PROPHETS, chapters: 3 },
  { name: 'Ageu', division: BibleDivision.MINOR_PROPHETS, chapters: 2 },
  { name: 'Zacarias', division: BibleDivision.MINOR_PROPHETS, chapters: 14 },
  { name: 'Malaquias', division: BibleDivision.MINOR_PROPHETS, chapters: 4 },

  // Novo Testamento
  { name: 'Mateus', division: BibleDivision.GOSPELS, chapters: 28 },
  { name: 'Marcos', division: BibleDivision.GOSPELS, chapters: 16 },
  { name: 'Lucas', division: BibleDivision.GOSPELS, chapters: 24 },
  { name: 'João', division: BibleDivision.GOSPELS, chapters: 21 },
  { name: 'Atos', division: BibleDivision.CHURCH_HISTORY, chapters: 28 },
  { name: 'Romanos', division: BibleDivision.PAULINE_EPISTLES, chapters: 16 },
  { name: '1 Coríntios', division: BibleDivision.PAULINE_EPISTLES, chapters: 16 },
  { name: '2 Coríntios', division: BibleDivision.PAULINE_EPISTLES, chapters: 13 },
  { name: 'Gálatas', division: BibleDivision.PAULINE_EPISTLES, chapters: 6 },
  { name: 'Efésios', division: BibleDivision.PAULINE_EPISTLES, chapters: 6 },
  { name: 'Filipenses', division: BibleDivision.PAULINE_EPISTLES, chapters: 4 },
  { name: 'Colossenses', division: BibleDivision.PAULINE_EPISTLES, chapters: 4 },
  { name: '1 Tessalonicenses', division: BibleDivision.PAULINE_EPISTLES, chapters: 5 },
  { name: '2 Tessalonicenses', division: BibleDivision.PAULINE_EPISTLES, chapters: 3 },
  { name: '1 Timóteo', division: BibleDivision.PAULINE_EPISTLES, chapters: 6 },
  { name: '2 Timóteo', division: BibleDivision.PAULINE_EPISTLES, chapters: 4 },
  { name: 'Tito', division: BibleDivision.PAULINE_EPISTLES, chapters: 3 },
  { name: 'Filemom', division: BibleDivision.PAULINE_EPISTLES, chapters: 1 },
  { name: 'Hebreus', division: BibleDivision.GENERAL_EPISTLES, chapters: 13 },
  { name: 'Tiago', division: BibleDivision.GENERAL_EPISTLES, chapters: 5 },
  { name: '1 Pedro', division: BibleDivision.GENERAL_EPISTLES, chapters: 5 },
  { name: '2 Pedro', division: BibleDivision.GENERAL_EPISTLES, chapters: 3 },
  { name: '1 João', division: BibleDivision.GENERAL_EPISTLES, chapters: 5 },
  { name: '2 João', division: BibleDivision.GENERAL_EPISTLES, chapters: 1 },
  { name: '3 João', division: BibleDivision.GENERAL_EPISTLES, chapters: 1 },
  { name: 'Judas', division: BibleDivision.GENERAL_EPISTLES, chapters: 1 },
  { name: 'Apocalipse', division: BibleDivision.APOCALYPSE, chapters: 22 },
];
